Fix addon.xml syntax error - Remove duplicate closing tag
Line 35 had duplicate </extension> tag causing XML parse error in Kodi.
Error: CAddonInfoBuilder::Generate: Unable to load addon.xml, Line 34

Fixed: Removed extra closing tag